/**
 * Stock API Service
 *
 * Fetches stock data from static JSON files (generated by GitHub Actions)
 * No backend server required - all data served from CDN
 */

import type { StockData, StockMetadata, Team } from '../types/stock';

// ============================================================================
// API CONFIGURATION
// ============================================================================

const DATA_BASE_URL = '/data';

// ============================================================================
// API FUNCTIONS
// ============================================================================

/**
 * Fetch all stock data (latest)
 */
export async function getAllStocks(): Promise<StockData[]> {
  try {
    const response = await fetch(`${DATA_BASE_URL}/stocks-latest.json`);

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data: StockData[] = await response.json();
    return data;
  } catch (error) {
    console.error('Error fetching stock data:', error);
    throw new Error('Failed to fetch stock data');
  }
}

/**
 * Fetch stock data for a specific date
 */
export async function getStocksByDate(date: string): Promise<StockData[]> {
  try {
    const response = await fetch(`${DATA_BASE_URL}/stocks-${date}.json`);

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data: StockData[] = await response.json();
    return data;
  } catch (error) {
    console.error(`Error fetching stock data for date ${date}:`, error);
    throw new Error(`Failed to fetch stock data for ${date}`);
  }
}

/**
 * Fetch metadata about the stock data
 */
export async function getStockMetadata(): Promise<StockMetadata> {
  try {
    const response = await fetch(`${DATA_BASE_URL}/metadata.json`);

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data: StockMetadata = await response.json();
    return data;
  } catch (error) {
    console.error('Error fetching metadata:', error);
    throw new Error('Failed to fetch metadata');
  }
}

/**
 * Filter stocks by team
 */
export function filterStocksByTeam(stocks: StockData[], team: Team): StockData[] {
  return stocks.filter((stock) => stock.team === team);
}

/**
 * Filter stocks by category
 */
export function filterStocksByCategory(
  stocks: StockData[],
  category: string
): StockData[] {
  return stocks.filter((stock) => stock.category === category);
}

/**
 * Filter stocks by sector
 */
export function filterStocksBySector(
  stocks: StockData[],
  sector: string
): StockData[] {
  return stocks.filter((stock) => stock.sector === sector);
}

/**
 * Get a single stock by ticker
 */
export function getStockByTicker(
  stocks: StockData[],
  ticker: string
): StockData | undefined {
  return stocks.find((stock) => stock.ticker === ticker);
}

/**
 * Filter historical data by date range
 */
export function filterHistoricalDataByDateRange(
  stocks: StockData[],
  startDate: string,
  endDate: string
): StockData[] {
  return stocks.map((stock) => ({
    ...stock,
    history: stock.history.filter(
      (dataPoint) => dataPoint.date >= startDate && dataPoint.date <= endDate
    ),
  }));
}

/**
 * Get unique sectors from stock data
 */
export function getUniqueSectors(stocks: StockData[]): string[] {
  return Array.from(new Set(stocks.map((stock) => stock.sector)));
}

/**
 * Get unique categories from stock data
 */
export function getUniqueCategories(stocks: StockData[]): string[] {
  return Array.from(new Set(stocks.map((stock) => stock.category)));
}

/**
 * Calculate aggregate market cap for a team
 */
export function calculateTeamMarketCap(stocks: StockData[], team: Team): number {
  return stocks
    .filter((stock) => stock.team === team)
    .reduce((total, stock) => {
      const latestMarketCap = stock.financials.marketCap || 0;
      return total + latestMarketCap;
    }, 0);
}

/**
 * Get Blue Team vs White Team comparison data
 */
export function getTeamComparison(stocks: StockData[]): {
  blueTeam: StockData[];
  whiteTeam: StockData[];
  blueTeamMarketCap: number;
  whiteTeamMarketCap: number;
} {
  const blueTeam = filterStocksByTeam(stocks, 'blue');
  const whiteTeam = filterStocksByTeam(stocks, 'white');

  return {
    blueTeam,
    whiteTeam,
    blueTeamMarketCap: calculateTeamMarketCap(stocks, 'blue'),
    whiteTeamMarketCap: calculateTeamMarketCap(stocks, 'white'),
  };
}

// ============================================================================
// CACHE HELPERS
// ============================================================================

/**
 * Cache configuration for React Query / TanStack Query
 */
export const STOCK_DATA_CACHE_CONFIG = {
  // Data is pre-generated daily, so we can cache indefinitely
  staleTime: Infinity,
  cacheTime: Infinity,
  refetchOnWindowFocus: false,
  refetchOnMount: false,
  refetchOnReconnect: false,
};
